### ISSUE TITLE
Update svelte template to use Svelte 5

### ISSUE THREAD

**Issue by Extarys** [aklinker1/vite-plugin-web-extension#215]
### Summary

Svelte 5 is out and the svelte template should be updated to use the latest version.

#### Is your feature request related to a bug/issue?

No

### Alternatives

Manually trying to update results in packing error when building:
![image](https://github.com/user-attachments/assets/d9d2fb3e-c4b8-4856-a7cb-aecfcab408fe)

In dev mode, the popup cannot be loaded
![image](https://github.com/user-attachments/assets/ea35f28f-a63e-4775-a09d-e7723978edb3)

```
	"devDependencies": {
		"@sveltejs/vite-plugin-svelte": "^3.1.1",
		"@tsconfig/svelte": "^5.0.4",
		"@types/webextension-polyfill": "^0.10.7",
		"svelte": "^5.0.3",
		"svelte-check": "^3.8.6",
		"tslib": "^2.6.3",
		"typescript": "^5.3.2",
		"vite": "^5.4.9",
		"vite-plugin-web-extension": "^4.1.6",
		"webextension-polyfill": "^0.10.0"
	}
```

(Testing with firefox)

### Additional Context

I believe I have the cors issue in dev mode even without the changes (fresh template) with svelte-ts.

**Comment by m-krebs** [comment]
Did you try to use sv migrate-5 script? With that I have no issues using Svelte 5.

**Comment by m-krebs** [comment]
Maybe I misunderstood your last point, but it looks like you want to keep the popup.ts the same as the template one? Because if that's so, then why is the reason to use svelte 5 syntax? If it's something else you mean, I apologize. 

In #216 I updated the svelte-js/ts templates to match the new svelte 5 syntax.

The error before, with `mount is not expoorted` should be solved by running your prefered npm install command, to replace the node modules of svelte with the new ones.

**Comment by m-krebs** [comment]
You're welcome, we are all on the same journey :)
